// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web_data.proto

#include "web_data.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace GameProto {
class RoleDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RoleData>
      _instance;
} _RoleData_default_instance_;
class TeamRoleDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TeamRoleData>
      _instance;
} _TeamRoleData_default_instance_;
}  // namespace GameProto
namespace protobuf_web_5fdata_2eproto {
void InitDefaultsRoleDataImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::GameProto::_RoleData_default_instance_;
    new (ptr) ::GameProto::RoleData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::GameProto::RoleData::InitAsDefaultInstance();
}

void InitDefaultsRoleData() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsRoleDataImpl);
}

void InitDefaultsTeamRoleDataImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_web_5fdata_2eproto::InitDefaultsRoleData();
  {
    void* ptr = &::GameProto::_TeamRoleData_default_instance_;
    new (ptr) ::GameProto::TeamRoleData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::GameProto::TeamRoleData::InitAsDefaultInstance();
}

void InitDefaultsTeamRoleData() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsTeamRoleDataImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GameProto::RoleData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GameProto::RoleData, qw_player_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GameProto::RoleData, sz_nick_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GameProto::RoleData, sz_avatar_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GameProto::RoleData, dw_sex_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GameProto::TeamRoleData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GameProto::TeamRoleData, role_data_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GameProto::TeamRoleData, dw_slot_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::GameProto::TeamRoleData, dw_server_id_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::GameProto::RoleData)},
  { 9, -1, sizeof(::GameProto::TeamRoleData)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::GameProto::_RoleData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::GameProto::_TeamRoleData_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "web_data.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016web_data.proto\022\tGameProto\"Y\n\010RoleData\022"
      "\024\n\014qw_player_id\030\001 \001(\004\022\024\n\014sz_nick_name\030\002 "
      "\001(\t\022\021\n\tsz_avatar\030\003 \001(\t\022\016\n\006dw_sex\030\004 \001(\r\"`"
      "\n\014TeamRoleData\022&\n\trole_data\030\001 \001(\0132\023.Game"
      "Proto.RoleData\022\022\n\ndw_slot_id\030\002 \001(\r\022\024\n\014dw"
      "_server_id\030\003 \001(\rb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 224);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "web_data.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_web_5fdata_2eproto
namespace GameProto {

// ===================================================================

void RoleData::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RoleData::kQwPlayerIdFieldNumber;
const int RoleData::kSzNickNameFieldNumber;
const int RoleData::kSzAvatarFieldNumber;
const int RoleData::kDwSexFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RoleData::RoleData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_web_5fdata_2eproto::InitDefaultsRoleData();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:GameProto.RoleData)
}
RoleData::RoleData(const RoleData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  sz_nick_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.sz_nick_name().size() > 0) {
    sz_nick_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sz_nick_name_);
  }
  sz_avatar_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.sz_avatar().size() > 0) {
    sz_avatar_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sz_avatar_);
  }
  ::memcpy(&qw_player_id_, &from.qw_player_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&dw_sex_) -
    reinterpret_cast<char*>(&qw_player_id_)) + sizeof(dw_sex_));
  // @@protoc_insertion_point(copy_constructor:GameProto.RoleData)
}

void RoleData::SharedCtor() {
  sz_nick_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sz_avatar_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&qw_player_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&dw_sex_) -
      reinterpret_cast<char*>(&qw_player_id_)) + sizeof(dw_sex_));
  _cached_size_ = 0;
}

RoleData::~RoleData() {
  // @@protoc_insertion_point(destructor:GameProto.RoleData)
  SharedDtor();
}

void RoleData::SharedDtor() {
  sz_nick_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sz_avatar_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RoleData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RoleData::descriptor() {
  ::protobuf_web_5fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_web_5fdata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RoleData& RoleData::default_instance() {
  ::protobuf_web_5fdata_2eproto::InitDefaultsRoleData();
  return *internal_default_instance();
}

RoleData* RoleData::New(::google::protobuf::Arena* arena) const {
  RoleData* n = new RoleData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RoleData::Clear() {
// @@protoc_insertion_point(message_clear_start:GameProto.RoleData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sz_nick_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sz_avatar_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&qw_player_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&dw_sex_) -
      reinterpret_cast<char*>(&qw_player_id_)) + sizeof(dw_sex_));
  _internal_metadata_.Clear();
}

bool RoleData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:GameProto.RoleData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 qw_player_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &qw_player_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string sz_nick_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sz_nick_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->sz_nick_name().data(), static_cast<int>(this->sz_nick_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "GameProto.RoleData.sz_nick_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string sz_avatar = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sz_avatar()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->sz_avatar().data(), static_cast<int>(this->sz_avatar().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "GameProto.RoleData.sz_avatar"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 dw_sex = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &dw_sex_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:GameProto.RoleData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:GameProto.RoleData)
  return false;
#undef DO_
}

void RoleData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:GameProto.RoleData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 qw_player_id = 1;
  if (this->qw_player_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->qw_player_id(), output);
  }

  // string sz_nick_name = 2;
  if (this->sz_nick_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sz_nick_name().data(), static_cast<int>(this->sz_nick_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GameProto.RoleData.sz_nick_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->sz_nick_name(), output);
  }

  // string sz_avatar = 3;
  if (this->sz_avatar().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sz_avatar().data(), static_cast<int>(this->sz_avatar().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GameProto.RoleData.sz_avatar");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->sz_avatar(), output);
  }

  // uint32 dw_sex = 4;
  if (this->dw_sex() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->dw_sex(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:GameProto.RoleData)
}

::google::protobuf::uint8* RoleData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:GameProto.RoleData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 qw_player_id = 1;
  if (this->qw_player_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->qw_player_id(), target);
  }

  // string sz_nick_name = 2;
  if (this->sz_nick_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sz_nick_name().data(), static_cast<int>(this->sz_nick_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GameProto.RoleData.sz_nick_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->sz_nick_name(), target);
  }

  // string sz_avatar = 3;
  if (this->sz_avatar().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sz_avatar().data(), static_cast<int>(this->sz_avatar().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "GameProto.RoleData.sz_avatar");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->sz_avatar(), target);
  }

  // uint32 dw_sex = 4;
  if (this->dw_sex() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->dw_sex(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GameProto.RoleData)
  return target;
}

size_t RoleData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GameProto.RoleData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string sz_nick_name = 2;
  if (this->sz_nick_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->sz_nick_name());
  }

  // string sz_avatar = 3;
  if (this->sz_avatar().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->sz_avatar());
  }

  // uint64 qw_player_id = 1;
  if (this->qw_player_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->qw_player_id());
  }

  // uint32 dw_sex = 4;
  if (this->dw_sex() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->dw_sex());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RoleData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:GameProto.RoleData)
  GOOGLE_DCHECK_NE(&from, this);
  const RoleData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RoleData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:GameProto.RoleData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:GameProto.RoleData)
    MergeFrom(*source);
  }
}

void RoleData::MergeFrom(const RoleData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:GameProto.RoleData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sz_nick_name().size() > 0) {

    sz_nick_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sz_nick_name_);
  }
  if (from.sz_avatar().size() > 0) {

    sz_avatar_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sz_avatar_);
  }
  if (from.qw_player_id() != 0) {
    set_qw_player_id(from.qw_player_id());
  }
  if (from.dw_sex() != 0) {
    set_dw_sex(from.dw_sex());
  }
}

void RoleData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:GameProto.RoleData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RoleData::CopyFrom(const RoleData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameProto.RoleData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RoleData::IsInitialized() const {
  return true;
}

void RoleData::Swap(RoleData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RoleData::InternalSwap(RoleData* other) {
  using std::swap;
  sz_nick_name_.Swap(&other->sz_nick_name_);
  sz_avatar_.Swap(&other->sz_avatar_);
  swap(qw_player_id_, other->qw_player_id_);
  swap(dw_sex_, other->dw_sex_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RoleData::GetMetadata() const {
  protobuf_web_5fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_web_5fdata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void TeamRoleData::InitAsDefaultInstance() {
  ::GameProto::_TeamRoleData_default_instance_._instance.get_mutable()->role_data_ = const_cast< ::GameProto::RoleData*>(
      ::GameProto::RoleData::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TeamRoleData::kRoleDataFieldNumber;
const int TeamRoleData::kDwSlotIdFieldNumber;
const int TeamRoleData::kDwServerIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TeamRoleData::TeamRoleData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_web_5fdata_2eproto::InitDefaultsTeamRoleData();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:GameProto.TeamRoleData)
}
TeamRoleData::TeamRoleData(const TeamRoleData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_role_data()) {
    role_data_ = new ::GameProto::RoleData(*from.role_data_);
  } else {
    role_data_ = NULL;
  }
  ::memcpy(&dw_slot_id_, &from.dw_slot_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&dw_server_id_) -
    reinterpret_cast<char*>(&dw_slot_id_)) + sizeof(dw_server_id_));
  // @@protoc_insertion_point(copy_constructor:GameProto.TeamRoleData)
}

void TeamRoleData::SharedCtor() {
  ::memset(&role_data_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&dw_server_id_) -
      reinterpret_cast<char*>(&role_data_)) + sizeof(dw_server_id_));
  _cached_size_ = 0;
}

TeamRoleData::~TeamRoleData() {
  // @@protoc_insertion_point(destructor:GameProto.TeamRoleData)
  SharedDtor();
}

void TeamRoleData::SharedDtor() {
  if (this != internal_default_instance()) delete role_data_;
}

void TeamRoleData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TeamRoleData::descriptor() {
  ::protobuf_web_5fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_web_5fdata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TeamRoleData& TeamRoleData::default_instance() {
  ::protobuf_web_5fdata_2eproto::InitDefaultsTeamRoleData();
  return *internal_default_instance();
}

TeamRoleData* TeamRoleData::New(::google::protobuf::Arena* arena) const {
  TeamRoleData* n = new TeamRoleData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TeamRoleData::Clear() {
// @@protoc_insertion_point(message_clear_start:GameProto.TeamRoleData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && role_data_ != NULL) {
    delete role_data_;
  }
  role_data_ = NULL;
  ::memset(&dw_slot_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&dw_server_id_) -
      reinterpret_cast<char*>(&dw_slot_id_)) + sizeof(dw_server_id_));
  _internal_metadata_.Clear();
}

bool TeamRoleData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:GameProto.TeamRoleData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .GameProto.RoleData role_data = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_role_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 dw_slot_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &dw_slot_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 dw_server_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &dw_server_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:GameProto.TeamRoleData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:GameProto.TeamRoleData)
  return false;
#undef DO_
}

void TeamRoleData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:GameProto.TeamRoleData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .GameProto.RoleData role_data = 1;
  if (this->has_role_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->role_data_, output);
  }

  // uint32 dw_slot_id = 2;
  if (this->dw_slot_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->dw_slot_id(), output);
  }

  // uint32 dw_server_id = 3;
  if (this->dw_server_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->dw_server_id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:GameProto.TeamRoleData)
}

::google::protobuf::uint8* TeamRoleData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:GameProto.TeamRoleData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .GameProto.RoleData role_data = 1;
  if (this->has_role_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, *this->role_data_, deterministic, target);
  }

  // uint32 dw_slot_id = 2;
  if (this->dw_slot_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->dw_slot_id(), target);
  }

  // uint32 dw_server_id = 3;
  if (this->dw_server_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->dw_server_id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GameProto.TeamRoleData)
  return target;
}

size_t TeamRoleData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GameProto.TeamRoleData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .GameProto.RoleData role_data = 1;
  if (this->has_role_data()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->role_data_);
  }

  // uint32 dw_slot_id = 2;
  if (this->dw_slot_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->dw_slot_id());
  }

  // uint32 dw_server_id = 3;
  if (this->dw_server_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->dw_server_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TeamRoleData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:GameProto.TeamRoleData)
  GOOGLE_DCHECK_NE(&from, this);
  const TeamRoleData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TeamRoleData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:GameProto.TeamRoleData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:GameProto.TeamRoleData)
    MergeFrom(*source);
  }
}

void TeamRoleData::MergeFrom(const TeamRoleData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:GameProto.TeamRoleData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_role_data()) {
    mutable_role_data()->::GameProto::RoleData::MergeFrom(from.role_data());
  }
  if (from.dw_slot_id() != 0) {
    set_dw_slot_id(from.dw_slot_id());
  }
  if (from.dw_server_id() != 0) {
    set_dw_server_id(from.dw_server_id());
  }
}

void TeamRoleData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:GameProto.TeamRoleData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TeamRoleData::CopyFrom(const TeamRoleData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GameProto.TeamRoleData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TeamRoleData::IsInitialized() const {
  return true;
}

void TeamRoleData::Swap(TeamRoleData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TeamRoleData::InternalSwap(TeamRoleData* other) {
  using std::swap;
  swap(role_data_, other->role_data_);
  swap(dw_slot_id_, other->dw_slot_id_);
  swap(dw_server_id_, other->dw_server_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TeamRoleData::GetMetadata() const {
  protobuf_web_5fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_web_5fdata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace GameProto

// @@protoc_insertion_point(global_scope)
